### ISSUE TITLE
question about reproduction

### ISSUE THREAD

**Issue by AmethystineAlpaca** [memray/OpenNMT-kpg-release#1]
I have run the evaluation for your trained model with the command provided in the readme file, and noticed that in all result csv files present_exact_f_score@5 and present_exact_f_score@10 are completely the same. I wonder if those are reasonable? if so, how can I reproduce the result shown in Table 1 of the 'paper Does Order Matter? An Empirical Study on Generating Multiple Keyphrases as a Sequence'?

**Comment by memray** [comment]
Hi,

`present_exact_f_score@5`, `present_exact_f_score@10` and `present_exact_f_score@k` are the results included in the paper (@k corresponds to F@O in paper). I think that the case may occur when the number of predicted or ground-truth keyphrases is less than 5 for all the data points. Can you check if `eval_topbeam=True` when you run the evaluation? It will only take the top-score generated sequence (self-terminating mode) and the number of predictions is usually small.

**Comment by AmethystineAlpaca** [comment]
Thanks, That explains my result.
