### ISSUE TITLE
Are documents without present target keywords used in evaluation?

### ISSUE THREAD

**Issue by matejMartinc** [memray/OpenNMT-kpg-release#11]
Hi,

I couldn't find this info in the paper, but am I correct to assume that the documents without any present target keywords (i.e., documents with just absent keywords) are not used in the final averaged f1 score calculation when measuring how well does the model predict present keywords? And also the other way around, documents containing just present keywords are not used when measuring how well does the model predict absent keywords, right? The function 'summarize_score' in kp_evaluate.py would imply that?

**Comment by memray** [comment]
You are right. Only valid documents (contain at least one present/absent phrase) are considered for averaging.

**Comment by matejMartinc** [comment]
Tnx!
