### ISSUE TITLE
about install

### ISSUE THREAD

**Issue by 980202006** [memray/OpenNMT-kpg-release#12]
Hi,
There is a setup.py file in the project. Is this project available for installation?If you import, do you use the import OpenNMT_py statement?

**Comment by memray** [comment]
Nope, no installation required. The setep.py was part of the original OpenNMT and I was not aware of it. Just run train.py together with a config file like `python train.py -config config/train/config-rnn-keyphrase-one2seq-diverse.yml`. I think these [scripts](https://github.com/memray/OpenNMT-kpg-release/tree/master/script) would also be useful.
