### ISSUE TITLE
How to run model on GPU?

### ISSUE THREAD

**Issue by waynedane** [memray/OpenNMT-kpg-release#13]
I ran 'python train.py -config config/train/config-rnn-keyphrase-one2seq-diverse.yml', but the model was training on cpu.
`[2020-07-12 08:39:48,866 INFO] encoder: 5199350`
`[2020-07-12 08:39:48,866 INFO] decoder: 8123008`
`[2020-07-12 08:39:48,866 INFO] * number of parameters: 13322358`
`[2020-07-12 08:39:49,071 INFO] Starting training on CPU, could be very slow`

**Comment by memray** [comment]
Have you solved this issue? There's an argument in the yml file (check the last few lines).

**Comment by arikanev** [comment]
Should gpu:-1 be changed to gpu:0?

**Comment by memray** [comment]
Just set valid gpu id in gpu_ranks, like L53 of this [file](https://github.com/memray/OpenNMT-kpg-release/blob/6725b530d52b756db7b60c69b261f9a8c372ce88/config/train/config-transformer-keyphrase-test.yml#L53).

**Comment by waynedane** [comment]
> Have you solved this issue? There's an argument in the yml file (check the last few lines).

I've solved, thanks.
