### ISSUE TITLE
Run the model on Custom Text

### ISSUE THREAD

**Issue by Rajmehta123** [memray/OpenNMT-kpg-release#15]
Great work. Thank you. 

The question is 

`"What are the steps to get keyphrase for the custom text?"
For eg: Some parameters where I could enter my text and the resulting output are the keyphrases or any other way by which I could insert custom documents.`

**Comment by memray** [comment]
Do you mean to run inference with your data? Check out this [notebook](https://github.com/memray/OpenNMT-kpg-release/blob/master/notebook/inference.ipynb) for reference. It might be a bit buggy and I cannot help with any technical issues recently. Hope it helps.

Best,
Rui
