### ISSUE TITLE
Is it possible to run eval script without having target data?

### ISSUE THREAD

**Issue by arikanev** [memray/OpenNMT-kpg-release#16]
Hi - sorry for the 2 issues in quick succession - can I run eval on data without targets?

**Comment by memray** [comment]
Hey,

It is possible. I upload a [notebook](https://github.com/memray/OpenNMT-kpg-release/blob/master/notebook/inference.ipynb) just for your reference.
It might be buggy since it was from another repo and I didn't test it here. Sorry about that and hope it helps.

Best,
Rui

**Comment by arikanev** [comment]
Thanks a ton! I started playing with the purely prediction script but I will look at this later.
