### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by shizhediao** [memray/OpenNMT-kpg-release#2]
Hi Memray,
I noticed that in the kp20k_test.tgt, examples are in the following format:
{"keywords": ["feedback vertex set", "decycling set", "2-degenerate graphs"], "id": "0", "tgt": ["feedback vertex set", "decycling set", "2 degenerate graphs"]}

I was wondering what's the difference bewteen keywords and tgt?
Which one are you using?
Thanks!

**Comment by memray** [comment]
Hi,

I use the tokenization method as mentioned in this [paper](https://arxiv.org/abs/1704.06879). Therefore `keywords` is the original data and `tgt` is the tokenized ones used for training the model.

Best,
Rui

**Comment by crystal0913** [comment]
Coutld tell me what's the format of kp20k_train.src ? I cannot download the ckpt&data.zip cause it's too big. Thanks!

**Comment by memray** [comment]
For both .src and .tgt, each line is a json string, which contains the tokenized source text or target text.
Check out this [small file](https://drive.google.com/file/d/1-H6DZyuEKi4pnw6kx0XPw6INuSmgqYww/view?usp=sharing) of KP20k test as an example.

Thanks,
Rui
