### ISSUE TITLE
Can't find magkp20k.vocab.pt

### ISSUE THREAD

**Issue by sjchasel** [memray/OpenNMT-kpg-release#27]
I downloaded the recently updated code and ran it. I can run ·`source kp_convert.sh` successfully. But when I run `python preprocess.py -config config/preprocess/config-preprocess-keyphrase-kp20k.yml` , it reported a error : `AssertionError: Please check path of your src vocab!`。 It seems like The src_vocab address is specified in the yml file, but there is no magkp20k.vocab.pt file at that address (`data/keyphrase/meng17/magkp20k.vocab.pt`) . Should I use `data/keyphrase/meng17/kp20k.vocab.pt` or What else should I do?

**Comment by memray** [comment]
`kp20k.vocab.pt` should work similarly. I upload the magkp20k vocab [here](https://drive.google.com/file/d/1vuZuU-XgACsuLEstOhNtgGs7LKy0LDcp/view?usp=sharing).

**Comment by sjchasel** [comment]
Thank you very much!
