### ISSUE TITLE
hugging-face models and datasets for keyphrase generation

### ISSUE THREAD

**Issue by zmf0507** [memray/OpenNMT-kpg-release#32]
do you have hugging face models and datasets for models and datasets  used in this repository? 
I cant find any on hugging-face page . Please let me know.

**Comment by zmf0507** [comment]
if I load the models from model.zip in hugging-face model wrapper, will it work ?

**Comment by zmf0507** [comment]
@memray can you answer my question?

**Comment by memray** [comment]
Hi @zmf0507, sorry for being late. 
No, I haven't done anything integrating HF features. I agree people may find it easier loading with HF APIs. Contributions are welcome and I would like to help as far as I can.

**Comment by zmf0507** [comment]
thanks, @memray for your help. 
Can you tell if there are any public hugging-face implementations available for keyphrase generation? I mean if there is any in your knowledge.

**Comment by memray** [comment]
No, as far as I know. I do feel it's handy and would definitely use it if it was available earlier  :)

**Comment by zmf0507** [comment]
thanks
