### ISSUE TITLE
Report an error

### ISSUE THREAD

**Issue by BiggyBing** [memray/OpenNMT-kpg-release#34]
Hi Meng,
I just found that the tgt_type supported in [opt.py](https://github.com/memray/OpenNMT-kpg-release/blob/c2ac57e585e62a14a037aed6caf27dc8f4e8c49f/onmt/opts.py#L652) is mismatched with that used [here](https://github.com/memray/OpenNMT-kpg-release/blob/c2ac57e585e62a14a037aed6caf27dc8f4e8c49f/onmt/inputters/keyphrase_dataset.py#L32). 

Can you please address it? Thanks in advance.

**Comment by memray** [comment]
Fixed! Many thanks!
