### ISSUE TITLE
Missing model files

### ISSUE THREAD

**Issue by helfardy** [memray/OpenNMT-kpg-release#41]
data.zip doesn't have the models/checkpoints (as specified in the readme)

**Comment by memray** [comment]
Sorry, I'm still refactoring the code. Will share the ckpts using the new code soon.

**Comment by jing86736238** [comment]
> Sorry, I'm still refactoring the code. Will share the ckpts using the new code soon.

So，we can not run this project ？

**Comment by memray** [comment]
You can, but you have to process raw text data to tensor files. New pipeline allows you to load from the raw data directly and tokenize it on the fly.
