### ISSUE TITLE
Is this project still working?

### ISSUE THREAD

**Issue by haseeb33** [memray/OpenNMT-kpg-release#42]
I am having many issues.
1. In newer torchtext (torchtext.data -> torchtext.legacy.data)
2. All the config files have data folder something like data/keyphrase/------ but original data uploaded on the drive has a different flow 
3. Due to a huge number of config files, it's very confusing where should I start. 

Any comments from the developers would be highly appreciated.

**Comment by memray** [comment]
Hi @haseeb33,

Sorry for being late. I'm still maintaining it but may not respond in time. I updated the code, mostly about integrating the new pre-processing pipeline from OpenNMT v2, so you can directly load [JSON data](https://drive.google.com/file/d/1z1JGWMnQkkWw_4tjptgO-dxXD0OeTfuP/view?usp=sharing) from disk, without the need of processing it to tensor files first. You can find some config examples [here](https://github.com/memray/OpenNMT-kpg-release/tree/master/script/empirical_study/diverse) using word tokenization (vocab [download](https://drive.google.com/file/d/1vuZuU-XgACsuLEstOhNtgGs7LKy0LDcp/view?usp=sharing)) and [here](https://github.com/memray/OpenNMT-kpg-release/tree/master/script/transfer/train_fulldata) using RoBERTa subtokens, for both RNN and Transformer. Hope this helps.

Thanks,
Rui

**Comment by haseeb33** [comment]
The shared vocab is in .pt format whereas the new implementation requires vocab in JSON format.

Please guide me in this regard!
Thanks!

**Comment by memray** [comment]
You are right. Check out the json file in this Google Drive [link](https://drive.google.com/drive/folders/1nJL-LC0M8lXdDEl0ZRQMc_rcuvvKO5Hb?usp=sharing).
