### ISSUE TITLE
Confusion of single-word phrase

### ISSUE THREAD

**Issue by shizhediao** [memray/OpenNMT-kpg-release#5]
Hi, thanks for your great work **_Deep Keyphrase Generation_**
I was really confused about the statement in section 4.3:

> In the generation of keyphrases, we find that the model tends to assign higher probabilities for shorter keyphrases, whereas most keyphrases contain more than two words. To resolve this problem, we apply a simple heuristic by preserving only the first single-word phrase and removing the rest.
What does that mean "preserve only the first single-word"?
Is it a post-processing step?
Could you give an example?
Thanks so much!

**Comment by memray** [comment]
It is a post-process (throw all single-word phrases away but the 1st one) and this heuristic is not used any longer. We found in many cases models output better results when this heuristic is not applied. Hope this answers your question.

Rui
