### ISSUE TITLE
AttributeError: module 'torchtext.data' has no attribute 'Iterator'

### ISSUE THREAD

**Issue by bahar-abbs** [memray/OpenNMT-kpg-release#50]
i use pytorch 1.11 and therefore torchtext 0.12
in this new version of torchtext, torchtext.data.Iterator dose not exist
so i don,t know what i have to do to run the code:
CUDA_VISIBLE_DEVICES=0 python onmt/keyphrase/kpg_example_hfdatasets.py
note that i m almost beginner in python

**Comment by bahar-abbs** [comment]
i'm really confused with your code. could you tell me, if i want to extract keyphrases from inspect data which code i have to run?

**Comment by bahar-abbs** [comment]
another question: :))
i want to use your Bart_wikiKp on my project
could you give me some explains about the dataset Wiki_kp which you used for finetuning bart

**Comment by ahadda5** [comment]
Just realized , my [issue ](https://github.com/memray/OpenNMT-kpg-release/issues/51) just created is related to this

**Comment by memray** [comment]
@bahar-abbs Please check out this [repo](https://github.com/memray/wikiextractor/blob/master/run_cmd.md) for processing wiki data (note: specify --dump_type phrase --json).
