### ISSUE TITLE
config/transfer_kp/train/transformer-presabs-kp20k.yml

### ISSUE THREAD

**Issue by Chunhui-Zou** [memray/OpenNMT-kpg-release#54]
Why can't I find the file:config/transfer_kp/train/transformer-presabs-kp20k.yml

**Comment by ahadda5** [comment]
Faced the same issue with other scripts. 
I guess the project is more than 4yrs old and it is continuously changing.  You can try an existing config yml.

**Comment by memray** [comment]
A mistake (I moved it to script/), it's now [here](https://github.com/memray/OpenNMT-kpg-release/tree/master/script/transfer/train_fulldata)
