### ISSUE TITLE
MAGKP dataset

### ISSUE THREAD

**Issue by ahadda5** [memray/OpenNMT-kpg-release#55]
I do not see the magpKP anywhere. It is mentioned in the 2021 NACLL "An empirical study on NEural Keyprahse Generation" paper . 

That is not found in the [data ](https://drive.google.com/open?id=1z1JGWMnQkkWw_4tjptgO-dxXD0OeTfuP) folder.  There exists the train db kp20 and stackex and the rest of the valid dbs. 

Should one ignore it?!

**Comment by memray** [comment]
Hi @ahadda5 . Sorry for recent slow updates. The paper is basically done and I will update the rest resources shortly, including the MagKP dataset. But you may consider process the data yourself (download MAG/OAG dump [here](https://www.microsoft.com/en-us/research/project/open-academic-graph/) and process it with this [script](https://github.com/memray/OpenNMT-kpg-release/blob/master/onmt/keyphrase/mag/export_mag_cs.py)). 

I used the v1 version MAG Papers, (9 zip files, like [mag_papers_0.zip](https://academicgraphv2.blob.core.windows.net/oag-v1/mag/mag_papers_0.zip)), which is smaller but more accessible.

**Comment by ahadda5** [comment]
Wow very kind of you! thanks Rui

**Comment by ahadda5** [comment]
also quick question,  on HuggingFace, i see the individual models (.pt) each trained on a certain dataset (kp20,openkp etc..) , however was there is no one trained on all? (in accordance with your finding "large and noisy datasets can benefit KPG" ? 

Thank you

**Comment by memray** [comment]
No, I didn't try training them all together. Maybe you can give it a try :D
