### ISSUE TITLE
about keyphrase representation in General-to-Specific Transfer Labeling for Domain Adaptable Keyphrase Generation

### ISSUE THREAD

**Issue by sjchasel** [memray/OpenNMT-kpg-release#57]
I note that you visualize phrases with T-SNE projection in your new paper. Could you tell me what method did you use to get the phrase representation？

**Comment by memray** [comment]
We used BERT-base to generate phrase embeddings: feed-forward each phrase independently as a
sequence and take the [CLS] embedding as the phrase embedding.
