### ISSUE TITLE
Potential bug?

### ISSUE THREAD

**Issue by shizhediao** [memray/OpenNMT-kpg-release#6]
I found that in ./onmt/inputters/inputter.py line 854

>         if opt.**model_dtype** == "keyphrase":
            batch_fn = keyphrase_dataset.max_tok_len
model_dtype = 'fp32' and model_type='keyphrase'
So I guess it should be :
>         if opt.**model_type** == "keyphrase":
            batch_fn = keyphrase_dataset.max_tok_len

**Comment by memray** [comment]
Good catch! Yes you are right, it should be **model_type**. Please fix it on your side. I will correct and push it later. Thank you!

**Comment by shizhediao** [comment]
Thanks for your reply!
But what confuses me is that the two batch_fns: keyphrase_dataset.max_tok_len and the original max_tok_len have the same definition.
Is it correct?
Thanks!

**Comment by memray** [comment]
Yes. I was planning to change it. It may be helpful to avoid OOM issue.
