### ISSUE TITLE
what's the full name of 'magkp'?

### ISSUE THREAD

**Issue by shizhediao** [memray/OpenNMT-kpg-release#7]
Hi,
I noticed in your preprocessing scripts, there is a kind of data called 'magkp'.

I guess it means one2many? but I can not get the full name. I was wondering what the full name of it.
Thanks!

**Comment by shizhediao** [comment]
by the way, if I want to train one2seq instead of one2one, which script should I refer?
What changes should I do?
Thanks!

**Comment by memray** [comment]
Sorry for the late reply.
Magkp is a dataset we are building now and we will release it soon.
Try these scripts [here](https://github.com/memray/OpenNMT-kpg-release/tree/master/script/srun_one2seq/train) for one2seq training.

Rui

**Comment by ahadda5** [comment]
Will this be published? or added to the [data ](https://drive.google.com/open?id=1z1JGWMnQkkWw_4tjptgO-dxXD0OeTfuP) folder.

**Comment by memray** [comment]
@ahadda5 I uploaded a MagKP subset (around 3m papers) at [here](https://drive.google.com/drive/folders/1nJL-LC0M8lXdDEl0ZRQMc_rcuvvKO5Hb?usp=sharing). But you can also use this [script](https://github.com/memray/OpenNMT-kpg-release/blob/master/onmt/keyphrase/mag/export_mag_cs.py) to process MAG data and you'll have around 12M papers.
