### ISSUE TITLE
# Confused for the experiment setting of transformer

### ISSUE THREAD

**Issue by lsj2408** [memray/OpenNMT-kpg-release#9]
Hi memray~
I have questions about the setting of transformer:

1) Which config file is related to the transformer arch in your paper "Does order matter"?
2) Do you have pretrained transformer model for releasing?

Thanks for your help~

**Comment by memray** [comment]
Hi @lsj2408 ,

I used some [scripts](https://github.com/memray/OpenNMT-kpg-release/blob/master/script/) to train different models. 
I don't have available transformers for now and they didn't perform better than RNN models. I'm running new training jobs and may release it later.

Thanks,
Rui
